### ISSUE TITLE
Channel numbers instead of channel names

### ISSUE THREAD

**Issue by nealey** [nealey/vail#29]
A user requested the channels be enumerated instead of named.

I think this might make things less confusing for a subset of users, and more confusing for a different set. But I could certainly replace the WPM channels with "Channel 1" through "Channel 3".

**Comment by rhughes71446** [comment]
enumerated Channels ch1, ch2 and ch3 would make it simpler to relay to another person…especially for example… if you are on HF CW and want to move to Vail, it’s not confusing to send “ch2” rather than “1-15wpm”.   Even if you are telling someone by voice, you still have to refer to “1-15wpm” as a channel for it to make sense. 

Also what is the purpose of the “channel” name “general chaos”?   Could this also be given a ch# ?

For those of us who are willing to spend time messing around non of this is a problem.  for the average user, The moment the can’t figure things out they will leave. 

For me personally, all is fine with program.  But…. I had a ham friend and very good and dedicated CW man leave the program due to not seeing things in the simplest of ways where it immediately made sense.

**Comment by nealey** [comment]
Getting rid of "General Chaos" is... complicated.

But I switched the WPM channels to just numbers, since nobody seemed attached to the WPM channels. Including me.

**Comment by nealey** [comment]
If people have suggestions for a different name than "General Chaos", I'm all ears, though. It's the default channel everybody gets when they open Vail, so the name needs to reflect that.

**Comment by ManOfMeans** [comment]
> Getting rid of "General Chaos" is... complicated.
> 
> But I switched the WPM channels to just numbers, since nobody seemed attached to the WPM channels. Including me.

Hi Neale,
I just checked the normal as well as testing sites and I still see the "1-15WPM"-type channel names.  A browser cache flush did not resolve.  Is it possible the update wasn't published?

**Comment by ManOfMeans** [comment]
> If people have suggestions for a different name than "General Chaos", I'm all ears, though. It's the default channel everybody gets when they open Vail, so the name needs to reflect that.

Well, since General Chaos is the default landing page when you join the site, my vote is to simply rename it to "Channel 1".
It's a communications channel, same as Channel 2, 3, etc. and I think the name should reflect that HI

**Comment by nealey** [comment]
Each repeater is specified by a string. The default landing repeater is actually the empty string `""`. I'm reluctant to give it a number, because I'm concerned that if, say, I made it "Channel 1", someone might think they could enter `1` in the repeater field and get that repeater, but they would instead get the repeater named `1` instead of the default landing repeater.

I suppose I could just change the client so you can never use the empty-string repeater, though.

**Comment by nealey** [comment]
We've been showing channel numbers 1-3 for a while now. People seem to think it's just dandy.
